# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f6ab3c4378244e782fb3f30b2e4ce524c09574ca79c0bf96caa70886c492e7055f5cce9e7a649e8150ea99bcca812eb523862a0e975b8522d77ecf5dcd0dd091

test:
  secret_key_base: 398510767f9575cde71fd84bea821566c4972542df5f0a3caa2851270de01b55ed2c916b0580249404f89eaf1b07d866d701214bfbd34be5e69ec1b826f8dbf6

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
